#!/usr/bin/env node

const fs = require('fs');
const tml = require('./tml');

const program = fs.readFileSync(0, 'utf-8');
const args = process.argv.slice(2);

console.log(`running: '${program}' with options: '${args.join(' ')}'`);

tml.onRuntimeInitialized = _ => {
	// load stuff from tml
	const { bdd, driver, options, output, strings } = tml;

	// initialize bdd database and driver's outputs
	bdd.init();
	driver.init();

	// create vector<string> arg_strings
	const arg_strings = new strings();
	args.forEach(arg => arg_strings.push_back(arg));

	// create options object and parse args
	const o = new options();
	o.parse(arg_strings);

	// console.log('args:', o.to_string());

	// create a driver and run program
	const d = driver.create(program, o);

	if (!d.result) console.log('unsat');

	// delete created objects
	d.delete(); o.delete(); arg_strings.delete();
};
