# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/troy/tau

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/troy/tau

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/troy/tau/CMakeFiles /home/troy/tau/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/troy/tau/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tml

# Build rule for target.
tml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tml
.PHONY : tml

# fast build rule for target.
tml/fast:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/build
.PHONY : tml/fast

bdd.o: bdd.cpp.o

.PHONY : bdd.o

# target to build an object file
bdd.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/bdd.cpp.o
.PHONY : bdd.cpp.o

bdd.i: bdd.cpp.i

.PHONY : bdd.i

# target to preprocess a source file
bdd.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/bdd.cpp.i
.PHONY : bdd.cpp.i

bdd.s: bdd.cpp.s

.PHONY : bdd.s

# target to generate assembly for a file
bdd.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/bdd.cpp.s
.PHONY : bdd.cpp.s

dict.o: dict.cpp.o

.PHONY : dict.o

# target to build an object file
dict.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/dict.cpp.o
.PHONY : dict.cpp.o

dict.i: dict.cpp.i

.PHONY : dict.i

# target to preprocess a source file
dict.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/dict.cpp.i
.PHONY : dict.cpp.i

dict.s: dict.cpp.s

.PHONY : dict.s

# target to generate assembly for a file
dict.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/dict.cpp.s
.PHONY : dict.cpp.s

driver.o: driver.cpp.o

.PHONY : driver.o

# target to build an object file
driver.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/driver.cpp.o
.PHONY : driver.cpp.o

driver.i: driver.cpp.i

.PHONY : driver.i

# target to preprocess a source file
driver.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/driver.cpp.i
.PHONY : driver.cpp.i

driver.s: driver.cpp.s

.PHONY : driver.s

# target to generate assembly for a file
driver.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/driver.cpp.s
.PHONY : driver.cpp.s

input.o: input.cpp.o

.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i

.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s

.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/input.cpp.s
.PHONY : input.cpp.s

lp.o: lp.cpp.o

.PHONY : lp.o

# target to build an object file
lp.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/lp.cpp.o
.PHONY : lp.cpp.o

lp.i: lp.cpp.i

.PHONY : lp.i

# target to preprocess a source file
lp.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/lp.cpp.i
.PHONY : lp.cpp.i

lp.s: lp.cpp.s

.PHONY : lp.s

# target to generate assembly for a file
lp.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/lp.cpp.s
.PHONY : lp.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/main.cpp.s
.PHONY : main.cpp.s

output.o: output.cpp.o

.PHONY : output.o

# target to build an object file
output.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/output.cpp.o
.PHONY : output.cpp.o

output.i: output.cpp.i

.PHONY : output.i

# target to preprocess a source file
output.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/output.cpp.i
.PHONY : output.cpp.i

output.s: output.cpp.s

.PHONY : output.s

# target to generate assembly for a file
output.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/output.cpp.s
.PHONY : output.cpp.s

query.o: query.cpp.o

.PHONY : query.o

# target to build an object file
query.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/query.cpp.o
.PHONY : query.cpp.o

query.i: query.cpp.i

.PHONY : query.i

# target to preprocess a source file
query.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/query.cpp.i
.PHONY : query.cpp.i

query.s: query.cpp.s

.PHONY : query.s

# target to generate assembly for a file
query.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/query.cpp.s
.PHONY : query.cpp.s

rule.o: rule.cpp.o

.PHONY : rule.o

# target to build an object file
rule.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/rule.cpp.o
.PHONY : rule.cpp.o

rule.i: rule.cpp.i

.PHONY : rule.i

# target to preprocess a source file
rule.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/rule.cpp.i
.PHONY : rule.cpp.i

rule.s: rule.cpp.s

.PHONY : rule.s

# target to generate assembly for a file
rule.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/rule.cpp.s
.PHONY : rule.cpp.s

transform.o: transform.cpp.o

.PHONY : transform.o

# target to build an object file
transform.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/transform.cpp.o
.PHONY : transform.cpp.o

transform.i: transform.cpp.i

.PHONY : transform.i

# target to preprocess a source file
transform.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/transform.cpp.i
.PHONY : transform.cpp.i

transform.s: transform.cpp.s

.PHONY : transform.s

# target to generate assembly for a file
transform.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/transform.cpp.s
.PHONY : transform.cpp.s

tree.o: tree.cpp.o

.PHONY : tree.o

# target to build an object file
tree.cpp.o:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/tree.cpp.o
.PHONY : tree.cpp.o

tree.i: tree.cpp.i

.PHONY : tree.i

# target to preprocess a source file
tree.cpp.i:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/tree.cpp.i
.PHONY : tree.cpp.i

tree.s: tree.cpp.s

.PHONY : tree.s

# target to generate assembly for a file
tree.cpp.s:
	$(MAKE) -f CMakeFiles/tml.dir/build.make CMakeFiles/tml.dir/tree.cpp.s
.PHONY : tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tml"
	@echo "... edit_cache"
	@echo "... bdd.o"
	@echo "... bdd.i"
	@echo "... bdd.s"
	@echo "... dict.o"
	@echo "... dict.i"
	@echo "... dict.s"
	@echo "... driver.o"
	@echo "... driver.i"
	@echo "... driver.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... lp.o"
	@echo "... lp.i"
	@echo "... lp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... query.o"
	@echo "... query.i"
	@echo "... query.s"
	@echo "... rule.o"
	@echo "... rule.i"
	@echo "... rule.s"
	@echo "... transform.o"
	@echo "... transform.i"
	@echo "... transform.s"
	@echo "... tree.o"
	@echo "... tree.i"
	@echo "... tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

