find_program(CLANG_TIDY NAMES run-clang-tidy-9 run-clang-tidy run-clang-tidy-10 run-clang-tidy.py)
if (CLANG_TIDY)
    set (CMAKE_EXPORT_COMPILE_COMMANDS ON)
    message(STATUS "Found clang-tidy")
    find_package(Python3)
    if (Python3_FOUND)
        cmake_host_system_information(RESULT CORE_COUNT QUERY NUMBER_OF_LOGICAL_CORES)
            add_custom_target(clang-tidy COMMAND python3 ${CLANG_TIDY} -quiet -j ${CORE_COUNT} -p "${CMAKE_BINARY_DIR}" -header-filter="${CMAKE_SOURCE_DIR}/src")
    else ()
        message(WARNING "Python >= 3.0 required")
    endif ()
else ()
    message(WARNING "CLANG_TIDY not found")
endif ()
