# populates GIT_DESCRIBED, GIT_BRANCH and GIT_COMMIT_HASH variables
# and creates GIT_DEFINITIONS list

execute_process(
	COMMAND git describe --tags --always
	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
	OUTPUT_VARIABLE GIT_DESCRIBED
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
	COMMAND git rev-parse --abbrev-ref HEAD
	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
	OUTPUT_VARIABLE GIT_BRANCH
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
	COMMAND git log -1 --format=%h
	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
	OUTPUT_VARIABLE GIT_COMMIT_HASH
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(GIT_DEFINITIONS
	"GIT_DESCRIBED=\"${GIT_DESCRIBED}\""
	"GIT_COMMIT_HASH=\"${GIT_COMMIT_HASH}\""
	"GIT_BRANCH=\"${GIT_BRANCH}\""
)
